/**
 * Markdown Exporter
 * Exports interpretations as formatted Markdown files with proper heading hierarchy
 */

class MarkdownExporter {
  /**
   * Export data as Markdown
   * @param {Object} data - Export data
   * @returns {string} Formatted Markdown content
   */
  export(data) {
    const sections = [];
    
    // Title (H1)
    sections.push('# 👻 The Haunted Reader - Export\n');
    
    // Metadata section
    sections.push(this._createMetadataSection(data.metadata));
    
    // Table of Contents
    sections.push(this._createTableOfContents(data.interpretations));
    
    // Original text section (H2)
    sections.push('## 📖 Original Text\n');
    sections.push(this._formatTextBlock(data.originalText));
    
    // Interpretations (H2 for each)
    for (const interpretation of data.interpretations) {
      sections.push(this._createInterpretationSection(interpretation));
    }
    
    // Footer
    sections.push(this._createFooter(data.metadata));
    
    return sections.join('\n\n');
  }

  /**
   * Create metadata section
   * @private
   */
  _createMetadataSection(metadata) {
    const lines = [
      '## 📋 Export Information\n',
      `**Export Date:** ${metadata.exportDate.toLocaleString()}  `,
      `**Spirits Summoned:** ${metadata.spiritsUsed.join(', ')}  `,
      `**Total Interpretations:** ${metadata.spiritsUsed.length}`
    ];
    return lines.join('\n');
  }

  /**
   * Create table of contents
   * @private
   */
  _createTableOfContents(interpretations) {
    if (interpretations.length === 0) {
      return '';
    }
    
    const lines = ['## 📑 Table of Contents\n'];
    lines.push('1. [Original Text](#-original-text)');
    
    interpretations.forEach((interp, index) => {
      const anchor = this._createAnchor(interp.spiritName);
      lines.push(`${index + 2}. [${interp.spiritName}](#${anchor})`);
    });
    
    return lines.join('\n');
  }

  /**
   * Create interpretation section
   * @private
   */
  _createInterpretationSection(interpretation) {
    const lines = [
      `## 🎭 ${interpretation.spiritName}\n`,
      '### Interpretation Details\n',
      `**Generated:** ${interpretation.generatedAt.toLocaleString()}  `,
      `**Word Count:** ${interpretation.wordCount}  `,
      `**Spirit ID:** \`${interpretation.spiritId}\`\n`,
      '### Content\n',
      this._formatTextBlock(interpretation.content)
    ];
    return lines.join('\n');
  }

  /**
   * Format text block with proper Markdown escaping
   * @private
   */
  _formatTextBlock(text) {
    // Preserve paragraph breaks
    const paragraphs = text.split(/\n\n+/);
    return paragraphs.join('\n\n');
  }

  /**
   * Create anchor link from spirit name
   * @private
   */
  _createAnchor(name) {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
  }

  /**
   * Create footer section
   * @private
   */
  _createFooter(metadata) {
    const lines = [
      '---\n',
      '## 🌙 About This Export\n',
      'This document was generated by **The Haunted Reader**, a multi-perspective text interpretation engine.',
      '',
      `Generated on ${metadata.exportDate.toLocaleDateString()} at ${metadata.exportDate.toLocaleTimeString()}`,
      '',
      '*May the spirits guide your reading...*'
    ];
    return lines.join('\n');
  }
}

export const markdownExporter = new MarkdownExporter();
export default markdownExporter;
