AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cognito Identity Pool and IAM Role for The Haunted Reader - Bedrock Access'

Parameters:
  IdentityPoolName:
    Type: String
    Default: HauntedReaderPool
    Description: Name for the Cognito Identity Pool
  
  RoleName:
    Type: String
    Default: HauntedReaderBedrockRole
    Description: Name for the IAM Role

Resources:
  # Cognito Identity Pool
  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Ref IdentityPoolName
      AllowUnauthenticatedIdentities: true
      AllowClassicFlow: false

  # IAM Role for Unauthenticated Users
  CognitoUnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref CognitoIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: unauthenticated
      Policies:
        - PolicyName: BedrockAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource:
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0'
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0'
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-text-express-v1'
      Tags:
        - Key: Application
          Value: HauntedReader
        - Key: Purpose
          Value: Kiroween Hackathon

  # Attach Role to Identity Pool
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        unauthenticated: !GetAtt CognitoUnauthenticatedRole.Arn

Outputs:
  IdentityPoolId:
    Description: Cognito Identity Pool ID (use in .env as VITE_COGNITO_IDENTITY_POOL_ID)
    Value: !Ref CognitoIdentityPool
    Export:
      Name: !Sub '${AWS::StackName}-IdentityPoolId'
  
  IdentityPoolArn:
    Description: Cognito Identity Pool ARN
    Value: !GetAtt CognitoIdentityPool.Arn
  
  RoleArn:
    Description: IAM Role ARN for Bedrock Access
    Value: !GetAtt CognitoUnauthenticatedRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
  
  RoleName:
    Description: IAM Role Name
    Value: !Ref CognitoUnauthenticatedRole
  
  Region:
    Description: AWS Region (use in .env as VITE_AWS_REGION)
    Value: !Ref AWS::Region
  
  EnvConfiguration:
    Description: Add these to your .env file
    Value: !Sub |
      VITE_AWS_REGION=${AWS::Region}
      VITE_COGNITO_IDENTITY_POOL_ID=${CognitoIdentityPool}
